#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("WeatherDemo.Resource", IsApplication=true)]

namespace WeatherDemo
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Broken = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int Chalk = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int Clear = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int FewClouds = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int Icon = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int Mist = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int Rain = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int Scatter = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int Showers = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int Snow = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int Thunder = 2130837514;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050000
			public const int bg = 2131034112;
			
			// aapt resource value: 0x7f05001b
			public const int btnConfirm = 2131034139;
			
			// aapt resource value: 0x7f050009
			public const int img1 = 2131034121;
			
			// aapt resource value: 0x7f05000d
			public const int img2 = 2131034125;
			
			// aapt resource value: 0x7f050011
			public const int img3 = 2131034129;
			
			// aapt resource value: 0x7f050015
			public const int img4 = 2131034133;
			
			// aapt resource value: 0x7f050019
			public const int img5 = 2131034137;
			
			// aapt resource value: 0x7f050005
			public const int linear5days = 2131034117;
			
			// aapt resource value: 0x7f050006
			public const int linearDay1 = 2131034118;
			
			// aapt resource value: 0x7f05000a
			public const int linearDay2 = 2131034122;
			
			// aapt resource value: 0x7f05000e
			public const int linearDay3 = 2131034126;
			
			// aapt resource value: 0x7f050012
			public const int linearDay4 = 2131034130;
			
			// aapt resource value: 0x7f050016
			public const int linearDay5 = 2131034134;
			
			// aapt resource value: 0x7f050001
			public const int linearLayout1 = 2131034113;
			
			// aapt resource value: 0x7f050004
			public const int txtCTemp = 2131034116;
			
			// aapt resource value: 0x7f050002
			public const int txtCity = 2131034114;
			
			// aapt resource value: 0x7f050007
			public const int txtDay1 = 2131034119;
			
			// aapt resource value: 0x7f05000b
			public const int txtDay2 = 2131034123;
			
			// aapt resource value: 0x7f05000f
			public const int txtDay3 = 2131034127;
			
			// aapt resource value: 0x7f050013
			public const int txtDay4 = 2131034131;
			
			// aapt resource value: 0x7f050017
			public const int txtDay5 = 2131034135;
			
			// aapt resource value: 0x7f05001a
			public const int txtSearch = 2131034138;
			
			// aapt resource value: 0x7f050008
			public const int txtTemp1 = 2131034120;
			
			// aapt resource value: 0x7f05000c
			public const int txtTemp2 = 2131034124;
			
			// aapt resource value: 0x7f050010
			public const int txtTemp3 = 2131034128;
			
			// aapt resource value: 0x7f050014
			public const int txtTemp4 = 2131034132;
			
			// aapt resource value: 0x7f050018
			public const int txtTemp5 = 2131034136;
			
			// aapt resource value: 0x7f050003
			public const int txtTime = 2131034115;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Place = 2130903041;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
